apiVersion: platform.bronze-deer.de/v1alpha1
kind: DataProduct
metadata:
  name: core5-dev
  namespace: dp-pnc-core5
spec:
  division: PNC
  env: DEV
  id: 5
  maintainers:
  - JAN
  name: core5
  warehouse:
    autoscale: false
    size: XSMALL
