apiVersion: platform.bronze-deer.de/v1alpha1
kind: DataProduct
metadata:
  name: tolle-presentation-dev
  namespace: dp-pnc-tolle-presentation
spec:
  division: PNC
  env: DEV
  id: 10
  maintainers:
  - JAN
  name: tolle-presentation
  viewers:
  - JAN
  warehouse:
    autoscale: true
    size: SMALL
