apiVersion: platform.bronze-deer.de/v1alpha1
kind: DataProduct
metadata:
  name: core6-dev
  namespace: dp-health-core6
spec:
  contributors:
  - JAN
  division: HEALTH
  env: DEV
  id: 7
  maintainers:
  - JAN
  name: core6
  viewers:
  - JAN
  warehouse:
    autoscale: false
    size: SMALL
