apiVersion: platform.bronze-deer.de/v1alpha1
kind: DataProduct
metadata:
  name: sdpcore-dev
  namespace: dp-pnc-sdpcore
spec:
  contributors:
  - JAN
  division: PNC
  env: DEV
  id: 1
  maintainers:
  - JAN
  name: sdpcore
  viewers:
  - JAN
  warehouse:
    autoscale: false
    size: XSMALL
