apiVersion: platform.bronze-deer.de/v1alpha1
kind: DataProduct
metadata:
  name: core4-dev
  namespace: dp-pnc-core4
spec:
  division: PNC
  env: DEV
  id: 4
  maintainers:
  - JAN
  name: core4
  warehouse:
    autoscale: false
    size: MEDIUM
