apiVersion: platform.bronze-deer.de/v1alpha1
kind: DataProduct
metadata:
  name: enablement-dev
  namespace: dp-pnc-enablement
spec:
  division: PNC
  env: DEV
  id: 6
  maintainers:
  - JAN
  name: enablement
  warehouse:
    autoscale: false
    size: XSMALL
